
<script language="Javascript">
document.write("<i>Muokattu viimeksi " + document.lastModified +". Tarkemmin ks. <a href='https://github.com/hrmJ/morfologia'>repositoriosta</a></i>");
</SCRIPT>

Tästä kurssista
===============

Kaksi kielentutkimuksen perinteistä päähaaraa ovat syntaksi ja morfologia. Siinä
missä syntaksi tutkii lauserakenteita ja sanojen tai lausekkeiden välisiä
suhteita, ovat morfologiassa kiinnostuksen kohteena ennen kaikkea sanat itse ja
se, mistä ne koostuvat.

Rohkaisuksi voin tässä vaiheessa todeta, että periaatteessa kyseessä on
eräänlainen kertauskurssi: kaikki kurssilla käsiteltävät asiat ovat sinulle jo
tuttuja aikaisemmista opinnoistasi. Tämän kurssin pointtina on, että opit
perusteellisemmin jäsentämään ja analysoimaan osaamistasi. Opit suomen- ja
venäjänkieliset termit ilmiöille, joihin ennen olet ehkä viitannut vain
ilmaisulla *"se ющий-päätteinen muoto"*. Samalla saat, toivottavasti, vastauksia
moniin *miksi*-kysymyksiin, kuten *miksi отец-sanan genetiivi on отца eikä отеца*.

Kurssilla käytettävä  saattaa olla sinulle jossain määrin
uudenlaisessa muodossa. Toivottavasti et pelästy -- yritykseni on tehdä
tästäkin "tylsästä kielioppikurssista" oikeasti motivoivaa ja nykyaikaista.
Samalla on pidettävä mielessä se, että kyseessä ovat yliopiston aineopinnot, ja
sitä kautta myös tilaisuus opetella syvällisempiä kielen analysoinnin
työkaluja.

Linkkejä
========

- [Kurssin termilista](termit.html)
- [Kurssin Moodle-alue](https://learning2.uta.fi/course/view.php?id=8679)
- [Kansalliskorpus](http://www.ruscorpora.ru)
- [wiktionary](http://ru.wiktionary.org)
- [Tihonovin sanakirja](http://http://old.kpfu.ru/infres/slovar1)
- [Zaliznjakin sanakirja](http://morfologija.ru)
- [Foneettinen sanakirja](http://slovonline.ru/slovar_el_fonetic/)
- [Internet-yhteisö kysymyksille ja vastauksille](http://rus.stackexchange.com/)

<!-- http://udarenieru.ru/  -->

Termeistä
=========

Kurssilla esiintyvät oleellisimmat termit pyritään keräämään [omalle erilliselle sivulleen](termit.html)
[https://mustikka.uta.fi/~juho_harme/morfologia/termit.html](https://mustikka.uta.fi/~juho_harme/morfologia/termit.html)


Kurssin aikataulu
=================

Luentojen aiheet voivat jonkin verran muuttua riippuen etenemistahdista.

no  | Pvm        | Aihe
--- | ---------- | ---------------------
1   | ti 30.8.   | Mikä ihmeen morfologia?
2   | ke 31.8.   | Morfien luokittelua + yleistä nomineista
-   | ti 6.9.    | EI LUENTOA (avajaiset)
3   | ke 7.9.    | Luku ja suku kieliopillisina kategorioina
4   | ti 13.9.   | Sija kieliopillisena kategoriana 
5   | ke 14.9.   | Sija kieliopillisena kategoriana 2
6   | ti 20.9.   | Vertailuaste. Sijat funktionaalisen morfologian kannalta: gen + dat
7   | ke 21.9.   | Sijat funktionaalisen morfologian kannalta: gen + dat + instr
8   | ti 27.9.   | Sijat funktionaalisen morfologian kannalta: nominatiivi + akkusatiivi (elollisuuskategoria)
9   | ke 28.9.   | Yleistä verbeistä
10  | ti 4.10.   | Persoona kieliopillisena kategoriana + Partisiippien muodostus
11  | ke 5.10.   | Pääluokka kieliopillisena kategoriana
12  | ti 11.10.  | Pääluokka + partisiipit funktionaalisen morfologian kannalta
-   | ti 18.10   | PERIODITAUKO
-   | ke 19.10   | PERIODITAUKO
13  | ke 19.10   | Aspekti kieliopillisena kategoriana
14  | ti 25.10.  | Aspektin muodostus ja aspektiparin käsite
15  | ke 26.10.  | Aspekti funktionaalisen morfologian kannalta 1
16  | ti 1.11.   | Aspekti funktionaalisen morfologian kannalta 2
17  | ke 2.11.   | Aika kieliopillisena kategoriana
18  | ti 8.11.   | Tapaluokka kieliopillisena kategoriana 1
19  | ke 9.11.   | Tapaluokka kieliopillisena kategoriana 2
20  | ti 15.11.  | Liikeverbit 1
21  | ke 16.11.  | Liikeverbit 2
22  | ti 22.11.  | Verbimuotoja: Gerundit
23  | ke 23.11.  | Verbimuotoja: Infinitiivi
24  | ti 29.11.  | Adverbien erityispiirteitä
25  | ke 30.11.  | Kertausta
26  | ti 6.12.   | EI LUENTOA (itsenäisyyspäivä)
26  | ke 7.12.   | KOE


Luento 1: Mikä ihmeen morfologia?
==================================

- [Takaisin sivun ylälaitaan](https://mustikka.uta.fi/~juho_harme/morfologia/#tästä-kurssista)
- [Lataa PDF](http://mustikka.uta.fi/~juho_harme/morfologia/materiaalit/luento1.pdf)
- [Tutki luentokalvoja](http://mustikka.uta.fi/~juho_harme/morfologia/presentations/luento1.html)
- [Tutki tuntitehtäviä](http://mustikka.uta.fi/~juho_harme/morfologia/tehtavat/luento1.pdf)

Tällä luennolla perehdytään lyhyesti siihen, mitä kaikkea morfologian alaan
kuuluu. Tarkastelemme, mitä aihealueita kurssilla käsitellään ja luomme
yleiskuvan kurssiluentojen sisällöstä ja tavoitteista.


Mitä ovat sanaluokat? 
---------------------

Sanaluokan käsite esitellään meille jo ala-asteikäisenä. Sanat muodostavat
kielessä enemmän tai vähemmän selviä ryhmiä: esimerkiksi lekseemeillä *книга*,
*стол* ja *разрушение* on jotain yhteistä ja ne eroavat lekseemeistä *играть*,
*слушать* ja *читать*, joilla puolestaan on keskenään jotakin yhteistä.
Sanaluokkien määrittely ei kuitenkaan ole yksiselitteistä. Mihin sanaluokkaan
mielestäsi esimerkiksi aktiivin partisiipin preesensin muoto "позволяющий"
kuuluu? Entä onko sanalla *тысяча* enemmän yhteistä sanojen *пять*, *десять* ja
*семь* kanssa kuin edellä mainittujen kolmen substantiivin kanssa? Ahti
Nikunlassi[-@nikunl: 123] on käsitellyt sanaluokkajaon ongelmia laajasti. Tällä
kurssilla palautetaan mieleen perinteistä sanaluokkajakoa, mutta kehotan
muistamaan, että sanaluokat eivät ole millään tavalla ylhäältä annettuja,
objektiivisia kategorioita, vaan enemmän tai vähemmän kompromissien tuloksena
syntynyt taksonomia eli luokittelu.

Slavistisessa perinteessä on tapana erotella toisistaan itsenäiset sanaluokat
(самостоятельные части речи) ja apusanaluokat (служебные части речи). Lisäksi
luokittelua voidaan jatkaa morfologisin perustein esimerkiksi niin, että
sijoissa taipuvia sanoja (käytännössä substantiiveja, adjektiiveja, lukusanoja, pronomineja)
kutsutaan yhteisesti *nomineiksi*. 

### Itsenäiset sanaluokat

- substantiivit (существительные)
- adjektiivit (прилагательные)
- pronominit (местоимения)
- lukusanat (числителные)
- verbit (глаголы)
- adverbit (наречия)

### Apusanaluokat

- prepositiot (предлоги)
- konjunktiot (союзы)
- partikkelit (частицы)
- interjektiot (междометия)


Mitä on sanan sisällä?
-----------------------


Ajattele vaikka pakettia lääkepillereitä -- kuvastakoon se lausetta tai laajemmin
tekstiä. Jos sinulta kysytään, mistä lääkepaketti koostuu, selkein vastaus
olisi *pillereistä*. Samaten vastaus kysymykseen *mistä lause koostuu* olisi
luultavasti *sanoista*. Kuitenkin se, mikä vaikutus pillereillä on 
jonkin sairauden parantamisessa, määräytyy sen mukaan, mistä ainesosista kukin
pilleri on tehty. Samoin sanojen kohdalla itse sanojen merkitys muodostuu sen
perusteella, mitä *morfeja* sanassa on.

Otetaan esimerkki. Ajattele sananmuotoa *выигриваю*. Jaetaan se morfeiksi:

(@ee_vyigrivaju) /вы/игр/ыва/ю/

Esimerkissä @ee_vyigrivaju on siis neljä morfia. Jokaisella näistä on jokin
merkitys -- jos jonkin näistä muuttaisi tai poistaisi, sanan merkitys muuttuisi.
Kokeile mielessäsi! Millä tavalla merkitys muuttuu, jos poistat ensimmäisen
morfin ja vaihdat hieman kolmatta? Entä jos vaihdat viimeisen morfin vaikka
morfiksi */ешь/*?

Kuten edellisestä käy ilmi, kielen pienintä, konkreettista yksikköä, joka kantaa
itsessään jotakin merkitystä, kutsutaan *morfiksi* (морф). Morfeja on tapana
merkitä laittamalla ne kauttaviivojen väliin (toinen vaihtoehto on erottaa
morfit esimerkiksi +-merkillä). Esimerkissä @ee_vyigrivaju
viimeinen morfi /ю/ tuo verbiin sen merkityksen, että toimintaa suorittaa
yksikön ensimmäinen persoona. Sanan varsinainen merkitys -- jota muut morfit
muokkaavat -- tulee toisesta morfista, */игр/*.

Katsotaan lisää esimerkkejä ja jaetaan ne samantien osiksi:

(@ee_peku) /пек/у/
(@ee_pechesh) /печ/ёшь/

Kummassakin yllä olevista esimerkeistä on kaksi morfia. Olet varmasti kuullut
myös sanan *morfeemi* (морфема). Siinä missä morfi on konkreettinen, yksittäinen
esiintymä, morfeemi on abstrakti yksikkö, joka voi esiintyä useampana erilaisena
morfina. Esimerkeissä @ee_peku ja @ee_pechesh on kummassakin morfeemi, jota
voitaisiin merkitä esimerkiksi {пек} tai {LEIPOA}[^morfmerk].
Tämän morfeemin konkreettisia esiintymiä ovat morfit /пек/ ja /печ/. Kyseessä
on siis yhden ja saman morfeemin kaksi konkreettista esiintymää, vähän niin kuin
jalkapallojoukkueessa {maalivahti}-"morfeemia" voivat edustaa "morfit" /Joe
Hart/ ja /Manuel Neuer/.

[^morfmerk] Kuten huomasit, morfeemeja merkitään asettamalla ne aaltosulkujen
sisään. Jos morfeemiin viitataan sen merkityksellä, se on tapana kirjoittaa
isolla.

Usein on niin, että jokin tietty morfeemi edustuu aina vain yhdellä, tietyllä
tavalla. Tällöin on käytännössä melkeinpä sama, puhutaanko morfeemista vai
morfista, mutta teoriassa erottelu toki tulee edelleen pitää mielessä. Jos
mietitään esimerkin @ee_vyigrivaju /игр/-morfia, voidaan todeta juuri näin:
morfeemia {игр} edustaa vain yksi morfi, /игр/. Morfeista /пек/ ja /печ/ voidaan
puolestaan vielä sanoa, että ne ovat toistensa *allomorfeja* (алломорф). Allomorfin käsite
kannattaa painaa mieleen nimenomaan suhteellisena käsitteenä: yksittäinen morfi
voi muodostaa allomorfiparin tai -kolmikon suhteessa joihinkin muihin morfeihin.

Jäitkö miettimään, mitä morfeemeja esimerkkien @ee_peku ja @ee_pechesh toiset
morfit (/у/ ja /ёшь/) edustavat? Kysymys on monimutkaisempi kuin ensi katsomalta
saattaisi olettaa. Liian informaatiotulvan välttämiseksi siirrän vastauksen
tuonnemmaksi ja palaan siihen, kun käsittelemme tarkemmin verbejä sanaluokkana.
Lisälukemiseksi tässä esitetyistä käsitteistä ks. esimerkiksi
[@musatov2016: 20; @nikunl: 104, @koivisto2013suomen: 66].

Älä pelästy, vaikka morfien erottelu ei aina ole selkeää. Voi olla, että sanasta
voisi löytyä enemmän osasia kuin luulit tai voi myös olla, että pilkot sanan
niin pieniksi palasiksi, ettei niillä kaikilla todellisuudessa ole omaa
merkitystä. Kurssin kuluessa erilaisiin morfeemeihin tutustutaan paremmin
ja tätä myötä myös kyky havaita niitä paranee.

### Morfien lajeja

Edellä sanoista puhuttaessa havaittiin, että niiden voi nähdä muodostavan
erilaisia ryhmiä. Myös morfeja tutkittaessa huomataan, että tietyillä morfeilla
on jotain yhteistä, joka taas erottaa ne joistakin muista morfeista.

Esimerkiksi edellä tarkemmin käsitellyissä morfeissa /игр/ ja /пек/ on selkeästi
jotakin yhteistä, jotakin erilaista verrattuna morfeihin /вы/, /ыва/, /ёшь/ jne.
Ensinmainitut morfit voidaan luokitella *juurimorfeiksi* (корневой морф, корень). Ne ilmaisevat
sanan varsinaisen leksikaalisen merkityksen: voisi sanoa, että ilman niitä muut
morfit ovat turhia. Muut morfit nimittäin eivät ilmaise leksikaalista vaan
*kieliopillista merkitystä*. Esimerkiksi esimerkin @ee_pechesh /ёшь/-morfi
ilmaisee toista persoonaa, indikatiivia ja ei-mennyttä aikaa. Nämä ovat hyvin
erityyppisiä merkityksiä kuin juurimorfin /пек/ leksikaalinen merkitys.
Kieliopilliset morfit voi jakaa moniin alaluokkiin, joita tutkitaan tarkemmin
seuraavalla luennolla. Näitä alalajeja ovat ennen kaikkea prefiksit, suffiksit,
interefiksit, postfiksit ja taivutuspäätteet.


Kieliopilliset kategoriat
-------------------------

Edellä puhuttiin *toisesta persoonasta*, *indikatiivista* ja *menneestä ajasta*.
Nämä ovat asioita, joita edellä käsitellyt morfeemit ilmaisevat. Tutkitaan lisää
vähän toisenlaisia sanoja:

(@ee_stolami) /стол/ами/
(@ee_krivaja) /крив/ая/

Esimerkin @ee_stolami /ами/-morfista voidaan sanoa, että se ilmaisee toisalta
monikkoa (sitä, että pöytiä on enemmän kuin yksi), toisaalta
instrumentaalisijaa. Esimerkin @ee_krivaja /ая/-morfi ilmaisee puolestaan
yksikköä, nominatiivisijaa ja lisäksi feminiinisukua.

Huomataan siis, että vaikka kieliopilliset morfit eivät sinänsä pysty
esiintymään yksinään, niillä silti ilmaistaan monenlaisia asioita. "Asia, jota
morfeemilla ilmaistaan" ei ole erityisen kätevä nimitys, mutta onneksi näihin
voidaan viitata kätevämmin termillä *kieliopillinen kategoria* (грамматическая
категория).
Venäjässä ilmaistavia kieliopillisia kategorioita ovat ainakin

- sukukategoria (категория рода)
- lukukategoria (категория числа)
- sijakategoria (категория падежа)
- elollisuuskategoria (категория одушевлённости)
- pääluokkakategoria (категория залога)
- persoonakategoria (категория лица)
- aspektikategoria (категория вида)
- tapaluokkakategoria (категория наклонения)
- aikamuotokategoria (категория времени)

Jos mietitään käsitteitä *instrumentaali*, *toinen persoona* tai *feminiini*,
voidaan sanoa, että ne ovat *kieliopillisten kategorioiden arvoja*. Palatakseni
jalkapallojoukkuemetaforaan voitaisiin kuvitella *pelipaikan* kieliopillinen
kategoria ja sille arvot *maalivahti*, *puolustaja*, *hyökkääjä* jne.
Yksi tämän kurssin tehtävistä on tutustua näihin kategorioihin ja 
konkreettisiin tapoihin, joilla kategorioiden eri arvoja eri sanoilla ilmaistaan.
Heti alkuun voidaan todeta, että läheskään kaikki sanat eivät ilmaise tai edes
voi ilmaista kaikkia kategorioita. Toiset kategoriat ovat tyypillisiä
esimerkiksi substantiiveille; joitain kategorioita ilmaisevat vain verbit.

On huomattava, että yksi morfi voi ilmaista useaa eri kieliopillista kategoriaa.
Venäjässä tämä on enemmän sääntö kuin poikkeus (vrt. kaikkia edellä käsiteltyjä
kieliopillisia morfeja!), ja tällaisille morfeille on oma nimityksensäkin:
salkkumorfi (гибридный морф) [ks. @nikunl, 106--107].


Millainen kieli venäjä on morfologian kannalta?
-----------------------------------------------

Kielten luokittelua erilaisten yhtenevien ja eriävien ominaisuuksien
perusteella kutsutaan kielitypologiaksi. Kun kieliä luokitellaan morfologisten
ominaisuuksien perusteella, on perinteisesti jaoteltu kieliä toisaalta
*synteettiisiin ja analyyttisiin*.

- Analyyttisiksi kutsutaan kieliä, jossa kieliopillisia suhteita ilmaistaan
  kieliopillisten sanojen (prepositiot, partikkelit, ym.) ja sanajärjestyksen avulla
- Synteettisiksi sanotaan kieliä, jossa kieliopillisia suhteita ilmaistaan
  taivutuspäätteiden avulla [vrt. @nikunl, 119]

Kumpaan ryhmään venäjä mielestäsi kuuluu?


Morfologian osa-alueita
-----------------------------------

- Sananmuodostusoppi (словообразование) ja taivutusoppi (словоизменение)

- Morfofonologia(морфонология), Morfosyntaksi (морфосинтаксис),
  Funktionaalinen morfologia (функциональная морфология)


Luento 2: morfeemityypeistä ja sanaluokista
=============================================

- [Takaisin sivun ylälaitaan](https://mustikka.uta.fi/~juho_harme/morfologia/#tästä-kurssista)
- [Lataa PDF](http://mustikka.uta.fi/~juho_harme/morfologia/materiaalit/luento2.pdf)
- [Tutki luentokalvoja](http://mustikka.uta.fi/~juho_harme/morfologia/presentations/luento2.html)
- [Tutki tuntitehtäviä](http://mustikka.uta.fi/~juho_harme/morfologia/tehtavat/luento2.pdf)

Morfeemien alalajeista tarkemmin
-----------------------------

Palataan toisen luennon aluksi tarkemmin eri morfeemityyppeihin. Edellä
todettiin, että kieliopillisia morfeemeja voidaan luokitella juurimorfeemeiksi, prefikseiksi, suffikseiksi,
postfikseiksi[^fikshuom], taivutuspäätteiksi ja interfikseiksi. Nämä voidaan jo
lähtökohtaisesti jakaa kahteen ryhmään: juurimorfeemeihin ja
*affikseihin* (аффиксы).
Tutkitaan kumpaakin ryhmää seuraavassa tarkemmin. Kun mietit yksittäisen sanan
jakautumista morfeihin, [wikisanakirja](http://ru.wiktionary.org) on kätevä ja
helppolukuinen paikka lähteä liikkeelle, josta löydät myös viitteet
'vakavampiin' kirjallisiin lähteisiin. Samoin internetissä on vapaasti käytettävissä E.A. Zaliznjakin sanakirjaan perustuva [morfologija.ru](http://www.morfologija.ru/), joka ei kuitenkaan niinkään jaa sanoja morfeiksi kuin esittelee eri taivutusparadigmoja. Wikisanakirjan lähteenä paljon käytetty [Tihonovin sanakirja](http://old.kpfu.ru/infres/slovar1) on myös vapaasti selattavissa oleva hyvä lähde. Kannattaa joka tapauksessa pitää mielessä,
ettei sanan jakaminen morfeiksi ole sekään millään lailla objektiivista,
itsenäistä todellisuutta vaan käytettävistä teoreettisista lähtökohdista
riippuvaisen tulkinnan tulos.

[^fikshuom]: Jos ihmettelet, miksi kaikki nämä nimitykset päättyvät
"fiksi/фикс", sanojen etymologia juontaa latinan *figere*-verbiin, jonka
merkitys on 'liittää, kiinnittää'.

### Juurimorfeemit

Juurimorfeemin käsitteeseen olemmekin jo törmänneet. Kuten Musatov
[-@musatov2016: 28] huomauttaa, venäjässä ei ole sanoja, joissa ei olisi
juurimorfia. Toisin sanoen jokaikisestä venäläisestä sanasta voidaan erottaa
*vähintään* juurimorfeemi. Juurimorfeemi ilmaisee sanan lähtökohtaisen
leksikaalisen merkityksen, jota muut morfeemit, esimerkiksi prefiksit, voivat
muokata. Joskus juurimorfi on ainoa morfi koko sanassa:

(@ee_avtor) /автор/

On kuitenkin huomattava, että vaikka juurimorfeemi on ainoa morfeemityyppi, joka
voi jo itsessään muodostaa sanan, aina näin ei kuitenkaan käy. Mieti esimerkiksi
sanoja одеть ja надеть. Missä niissä on juurimorfi ja voisiko se esiintyä
itsenäisenä sanana?

Sanojen одеть ja надеть juurimorfeiksi voidaan erottaa /де/. Tällaisia
ei-itsenäisinä esiintyvä morfeemeja nimitetään sidotuiksi (связанные) erotuksena
vapaista (свободные) juurimorfeemeista.

### Affiksit

#### Prefiksit ja  suffiksit

Prefiksejä (префиксы)[^pristavka] ja suffikseja (суффиксы) käytetään muodostettaessa uusia
sanoja. Ne eivät siis liity taivuttamiseen, vaan ennen kaikkea *johtamiseen* ja
*sananmuodostukseen* (vrt. päätteet alla). Tarkastellaan aluksi erityisen selkeää tapausta:

[^pristavka]: Venäläisperäisempi termi olisi приставка. Tieteellisessä
diskurssissa on kuitenkin parempi käyttää префикс-termiä. Vrt. myös ero suomen
*prefiksi*- ja *etuliite*-sanojen välillä.

(@ee_soavtor) /со/автор/

Esimerkissä @ee_soavtor on prefiksi /со/, joka muuttaa автор-sanan merkitystä ja
muodostaa kokonaan uuden sanan, jonka merkitys ('toinen mukana ollut
kirjoittaja', 'kanssakirjoittaja') tässä tapauksessa on helppo ymmärtää
ikään kuin muokatuksi juurimorfeemin merkitykseksi. Myös edellä mainituissa
надеть- ja одеть-sanoissa juurimorfia /де/ edeltävää ainesta voidaan nimittää
prefiksiksi (morfit /на/ ja /о/). Ne muokkaavat juuresta uuden sanan, vaikka
tässä tapauksessa itse juuri ei sanana esiinnykään.
Tavallisia prefiksejä ovat esimerkiksi *пере-*,*за-*,*от-*,*с-* jne.

Suffiksit eroavat prefikseistä siten, että siinä missä prefiksit sijoittuvat
*ennen* juurimorfeemia, sijoittuvat suffiksit juurimorfeemin *jälkeen*. Myös
suffiksit ovat etupäässä sananmuodostuksellisia morfeemeja. Suffikseista voisi
todeta, että muun muassa äänteenmuutosten takia niitä on välillä vaikea erottaa,
niin että suffikseja on usein sielläkin, missä ensi katsomalta ei siltä näyttäisi.
Helposti havaittavissa on esimerkiksi adjektiivista /хитр/- juurimorfiin
liitetty ость-suffiksi esimerkissä @ee_hitrost:

(@ee_hitrost) /хитр/ость/

Vaikeammin havaittavia ovat esimerkiksi verbinmuodostussuffiksit /и/ ja /а/:

(@ee_utshitel) уч/и/ть
(@ee_igrat2) игр/а/ть

Muita tyypillisiä suffikseja ovat esimerkiksi /ик/,/ец/,/тель/ jne.

Sekä prefikseistä että suffikseista on huomattava, että niitä voi sanassa olla
useita. Mitä prefiksejä ja suffikseja voit erottaa seuraavista sanoista?

(@ee_pereodevat) переодеваю
(@ee_osnovatelnitsa) основательницу

Prefiksejä ja suffikseja ei ole ääretöntä määrää, vaan halutessaan
tavallisimmat voi opetella vaikka ulkoa. Erilaisia substantiiveiin liitettäviä
suffikseja on listannut muun muassa Šeljakin [-@sheljakin: 32--37].

#### Taivutuspäätteet

Taivutuspäätteillä ei muodosteta uusia sanoja vaan ilmaistaan eri kieliopillisia
kategorioita ja niiden arvoja (vrt. prefiksit ja suffiksit yllä).
Taivutuspäätteet sijaitsevat sanassa prefiksian, juurien ja suffiksien jälkeen. Tutki
esimerkiksi seuraavaa худой-adjektiivin sananmuotoa:

(@ee_huduju) /худ/ую/

/ую/ on taivutuspääte (окончание), joka ilmaisee useampaakin kieliopillista kategoriaa:
lukua (arvona tässä yksikkö), sukua (feminiini, женский род) ja sijaa (akkusatiivi, винительный падеж).
Osin toisenlaisista taivutuspäätteistä on kyse seuraavissa esimerkeissä:

(@ee_guljala) /гул/я/л/а/
(@ee_kniga) /книг/а/
(@ee_obed) /обед/ø/

Esimerkissä @ee_guljala on itse asiassa kaksi päätettä, /л/, joka ilmaisee
aikamuotoa (mennyt aika, продщее время) ja /а/ joka ilmaisee lukua ja sukua (yksikkö,
feminiini). Esimerkki @ee_obed on merkittävä siinä mielessä, että se esittelee
*nollamorfin* (нулевой морф) käsitteen. Voidaan nimittäin katsoa, että
обед-sanassakin on -- kuten книга-sanassa -- sukua ilmaiseva pääte. Tämä vain ei
edustu jonakin sarjana foneemeja vaan nimenomaan äänteiden puuttumisena.
Nollamorfia merkitän symbolilla ø. Käsitteeseen palataan vielä kurssin edetessä,
joten ei kannata pelästyä, vaikka sen merkitys jäisi jonkin verran avoimeksi.

Taivutuspäätteistä käytetään joskus pääte/окончание-nimitysten lisäksi termiä
fleksio (флексия).


#### Postfiksit ja interfiksit

Prefiksit ja suffiksit ovat erittäin yleisiä morfeemityyppejä. Sen sijaan sekä
*postfikseja* (постфиксы) että etenkin *interfiksejä* (интерфиксы) esiintyy
huomattavasti harvemmin. Postfiksit ovat periaatteessa sananmuodostuksen
palveluksessa olevia morfeemeja, jotka sijoittuvat prefiksien, juuren,
suffiksien ja taivutuspäätteiden jälkeen, siis nimensä mukaisesti viimeiselle
mahdolliselle paikalle sanassa. Venäjän tavallisimpia postfiksejä ovat -нибудь,
-то, -либо sekä ehkä tavallisimmin vastaan tuleva verbeillä esiintyvä -cя.
Interfiksit puolestaan ovat -- nekin nimensä mukaisesti -- sanojen välissä
olevia liitosmorfeemeja, joiden avulla muodostetaan yhdyssanoja:

(@ee_thsernobelyj) /чёрн/о/бел/ый/

### Vartalo

Vartalon (основа) käsitteeseen palataan tarkemmin käsiteltäessä kieliopillisten
kategorioiden konkreettisia arvoja. Jo tässä vaiheessa on paikallaan todeta,
että vartalon käsitettä ei kannata sekoittaa juurimorfeemin käsitteeseen. Itse
asiassa vartalo ei useinkaan koostu vain yhdestä, vaan itse asiassa useammasta
morfeemista. Vartaloksi nimittäin sanotaan sitä osaa sanasta, joka jää jäljelle,
kun postetaan taivutuspäätteet, esimerkiksi (vartalo erotettu kursiivilla):

(@ee_prepodovatelja) */преподава/тел*/я/


Morfofonologisista vaihteluista
-------------------------------

Edellisellä luennolla mainittiin, että yksi morfologian alalajeista on nimeltään
morfofonologia (морфонология). Morfofonologialla on kielenkäyttäjän kannalta
paljon käytännön merkitystä. Tämä johtuu siitä, että morfofonologia tutkii muun
muassa *äänteenmuutoksia* (чередования). Juuri äänteenmuutokset saavat usein
aikaan vaikutelman siitä, että esimerkiksi verbien persoonataivutuksessa on "pelkkiä
poikkeuksia" tai muotoja, joita ei voi ennustaa. Tosiassa nämä muodot ovat usein
täysin säännnmukaisia, mutta niissä vain tapahtuu yhtälailla säännönmukaisia
konsonanttien tai vokaalien vaihteluita. Katsomme tässä yhteydessä vain lyhyesti
yhtä esimerkkiä ja palaamme morfofonologisiin vaihteluihin muun muassa
substantiivien sija- ja verbien persoonakategorian käsittelyn yhteydessä.

Ehkäpä kaikkein tavallisin äänteenmuutos on liudentuneiden ja liudentumattomien
konsonanttien vaihtelu. Vain kirjoitettua sanaa katsoessa ei ehkä tulisi
ajatelleeksikaan, että seuraavat äänneparit [@musatov2016: 148-149] eivät itse
asiassa edusta saman äänteen kahta eri versiota vaan kahta eri äännettä -- kahta
eri foneemia:

- р -- р'
- м -- м'
- д -- д'
- т -- т'
- н -- н'
- с -- с'
- б -- б'
- л -- л'
- ф -- ф'
- г -- г'
- х -- х'
- к -- к'
- в -- в'
- з -- з'
- п -- п'


Ajattele tässä valossa esimerkkiä @ee_kotik. Lisättäessä juurimorfiin /кот/
suffiksi /ик/ morfin viimeinen foneemi vaihtuu eli äänne [т] muuttuu äänteeksi
[т'] -- tämä ero vain ei näy ortografian tasolla, kirjoituksessa.

(@ee_kotik) кот -- котик

Tietyissä tapauksissa ero voidaan havaita ortografiankin tasolla:

(@ee_putnik) путь -- путник

esimerkissä @ee_putnik liudentunut [т']-äänne vaihtelee liudentumattoman
[т]-äänteen kanssa, mikä näkyy pehmeän merkin puuttumisena путник-sanan
kirjoitusasusta.

Paljon näitä sananmuodostukseen liittyviä esimerkkejä konkreettisemmin
äänteenmuutokset näyttäytyvät, kuten mainittua, taivutuksessa. Tavallisimpia
tapauksia [ks. @musatov2016: 158] ovat esimerkiksi [з']/[ж]-vaihtelu
(@ee_morozit), [т']/[ч]-vaihtelu (@ee_platit) ja [с']/[ш]-vaihtelu (@ee_kosit):

(@ee_morozit) морозить -- морожу
(@ee_platit) платить -- плачу
(@ee_kosit) косить -- кошу

Listaa tavallisista äänteenmuutoksista voi tutkia esimerkiksi [@sheljakin:
21-22].

Tällä kurssilla morfit merkitään aina kun mahdollista tavallisen kirjoitusasun
mukaisesti. Jos huomio kuitenkin on esimerkiksi äänteenmuutoksissa, saatetaan
käyttää foneettista merkintätapaa.


Substantiivit, adjektiivit, pronominit, lukusanat
-------------------------------------------------

Tulevilla luennoilla aletaan tarkemmin perehtyä eri kieliopillisiin
kategorioihin ja niiden arvoihin. Aloitamme luku-, suku- ja sijakategorioista,
jotka ovat erityisen olennaisia substantiiveilla, mutta myös adjektiiveillä,
pronomineilla ja lukusanoilla. Ennen kuin siirrytään varsinaisiin
kieliopillisten kategorioiden arvoihin ja toisaalta niiden käyttöön käytännössä
(funktionaaliseen morfologiaan), on syytä tutkia hivenen tarkemmin, mitä
erityispiirteitä mainittuihin sanaluokkiin liittyy. Kun myöhemmin siirrytään
käsittelemään verbejä, otetaan uudestaan käsittelyyn myös nämä kategoriat niiltä osin kuin ne
verbeillä edustuvat.

### Substantiivit

Substantiivit ovat venäjän yleisin sanaluokka: Venäjän kansalliskorpuksen
pääaineiston sanoista 28,5% on substantiiveja. Substantiivit ilmaisevat niin
sukua, lukua, sijaa kuin elollisuuttakin.

Substantiiveja voidaan luonnollisesti jaotella edelleen esimerkiksi semanttisin
perustein (merkityksen mukaan). Voidaan erotella *yleisnimet* (имена
нарицательные) ja
erisnimet (имена собственные).
Toisaalta voidaan puhua abstrakteista tai konkreettisista substantiiveista.
Lisäksi oma ryhmänsä ovat ainesanat kuten каша, нефть ym.
Substantiivit toimivat erityisen usein lähtökohtina muiden sanaluokkien sanojen
muodostukselle [ks. @musatov2016: 312--].

### Adjektiivit

Myös adjektiivit ilmaisevat suku- luku- ja sijakategorioita sekä ainakin
välillisesti elollisuuttakin. Niiden erikoisuus ovat lisäksi *vertailuasteet*
(степени сравнения), joita niiden lisäksi ilmaisevat vain adverbit.

Adjektiivit esiintyvät venäjässä *pitkinä* ja *lyhyinä* muotoina (длинные и
короткие формы прилагательных).
Lyhyiden muotojen käyttö on syntaktisesti rajoitettua: ne toimivat ainoastaan
predikatiiveina, kuten esimerkissä @ee_tufli.

(@ee_tufli) Скандинавская кухня *лаконична* в средствах и *многообразна* в методах


### Pronominit

Pronominit ilmaisevat (joskin vaihtelevasti) luku-, suku- ja sijakategorioita
sekä ainoana sanaluokkana verbien lisäksi myös persoonakategoriaa. Erotuksena
verbeistä persoonan ilmaiseminen ei tapahdu pronomineilla taivutuspäätteen vaan
sanavartalon avulla [@nikunl, 154]. Erityisesti persoonapronominit ovat
taivutuksen suhteen omalaatuinen luokka, jonka sisällä on suurta vaihtelua.
Tähän palataan tarkemmin luennolla 5. Pronominien erikoisuuksiin morfologian
kannaltaa kuuluu myös se, että niistä on usein hankala erottaa juurimorfeemia ja
taivutuspäätteitä. Ajettele vaikka sananmuotoja *мне* ja  *меня* ja vertaa niitä
nominatiivimuotoon *я*.


### Lukusanat

Lukusanat ovat, kuten edellä mainittiin, osittain hämärästi määriteltävissä
oleva luokka, johon luetaan usein morfologiselta rakenteeltaan hyvin erilaisia
sanoja. Läheskään kaikki lukusanat eivät, nurinkurista kyllä, ilmaise
luvun kieliopillista kategoriaa (niillä ei ole erillisiä yksikkö- ja
monikkomuotoja). Myöskään sukua lukusanat eivät paria poikkeusta lukuunottamatta
ilmaise. Lukusanat onkin oma luokkansa ennen muuta sen takia, että
tähän ryhmään yleensä luettavat sanat ovat merkityksen puolesta lähellä toisiaan
[tarkemmin ks. @nikunl: 123]. Morfologiselta kannalta kannattaa kiinnittää
huomio seuraaviin luokansisäisiin jakoihin:

#### Järjestysluvut (порядковые числительные) ja peruslukusanat (количественные числителные).

Järjestysluvut (esimerkiksi *пятый*) toimivat monessa suhteessa adjektiivien
tavoin. Niillä ei kuitenkaan ole vertailuasteita tai erillisiä lyhyitä ja pitkiä
muotoja.

#### Perusluvut 1-4 ja muut luvut

Peruslukusanatkaan eivät ole täysin yhtenäinen joukko. Oma erillistapauksensa on
ensinnäkin lukusana *один*, joka ilmaisee sukukategoriaa (vrt. muodot одна, одно
jne), lukukategoriaa (один vs. одни) ja taipuu esimerkiksi sijoissa paljolti adjektiivien tavoin. Luvuilla 2-4
on hyvin erilaiset taivutusparadigmat (konkreettiset kieliopillisten
kategorioitten, kuten sijan, arvot) kuin muilla luvuilla. Peruslukusanat
ovat siinäkin suhteessa erikoinen luokka, että nominatiivissa ne toimivat
pääsanana ja määrävät niihin liittyvän substantiivin sijan (семь столов), mutta
muuten käyttäytyvät syntaktisessa mielessä adjektiivien tavoin (без семи столов).

#### Morfologiset substantiivit 

Lukusanoiksi voidaan merkityksensä puolesta luetella myös sanat миллион,
миллиард ja тысяча, vaikka ne taipuvat kuten mitkä tahansa substantiivit ja
ilmaisevat niin suku-, luku- kuin sijakategorioita.


#### Kollektiivilukusanat

Oma alauokkansa lukusanojen sisällä ovat kollektiivilukusanat (*двое*, *трое*
ym.) joiden käyttöympäristöt ovat melko rajattuja. Nekään eivät ilmaise lukua
eli eivät tee eroa yksikön ja monikon välillä.



Luento 3: luku ja suku kieliopillisina kategorioina
========================================================

- [Takaisin sivun ylälaitaan](https://mustikka.uta.fi/~juho_harme/morfologia/#tästä-kurssista)
- [Lataa PDF](http://mustikka.uta.fi/~juho_harme/morfologia/materiaalit/luento3.pdf)
- [Tutki luentokalvoja](http://mustikka.uta.fi/~juho_harme/morfologia/presentations/luento3.html)
- [Tutki tuntitehtäviä](http://mustikka.uta.fi/~juho_harme/morfologia/tehtavat/luento3.pdf)

Luku kieliopillisena kategoriana
--------------------------------

Kuten edellä todettiin, lukukategoria (категория числа) koostuu venäjässä tasan kahdesta
vaihtoehdosta, joiden suhteen sananmuodot ovat oppositiossa keskenään: jos
sanat ilmaisevat lukua, ne ilmaisevat joko *yksikköä* (единственное число) tai monikkoa (множественное число). 

Voidaan sanoa, että luvun *oletusarvo* on yksikkö [@nikunl: 147]. Näin voidaan
päätellä, koska monet sananmuodot eivät voi olla ilmaisematta lukua: esimerkiksi
verbin *стать* preteritimuoto ilmaisee aina joko yksikköä tai monikkoa
(стал,стала,стало,стали). Jos lauseessa ei ole elementtiä, joka ohjaisi
(kongruenssi / согласование) käyttämään jompaakumpaa, valitaan yksikkö, niin kuin esimerkissä
@ee_stalo:


(@ee_stalo) Бабушке стало лучше.


Tarkastellaan seuraavassa muutamaa lukukategoriaan liittyvää erityistapausta.


### Erikoistapauksia


Substantiiveilla lukukategorian ilmaisemiseen liittyy kaksi erityistapausta:
niin kutsutut *pluralia tantum*- ja *singularia tantum* -sanat. Kummatkaan
näistä sanaryhmistä eivät käytännössä ilmaise lukukategoriaa [@nikunl: 147].

Pluralia tantum -sanat ovat aina monikossa, singularia tantum -sanat puolestaan
aina yksikössä esiintyviä sanoja. Pluralia tantum -sanat ovat selvärajaisempi
luokka (siihen kuuluu venäjässä noin 600 sanaa) siinä mielessä, että singularia
tantum -ryhmän sanoilla voi usein tietyissä käyttötapauksissa tulkita olevan
monikkomuodonkin.

Mahdollisesti tulevina kielenopettajina kannattaa kiinnittää näihin sanaryhmiin
huomiota siinä suhteessa, että vaikka mainitut ilmiöt ovat olemassa niin
suomessa kuin venäjässä, eivät niihin kuuluvien sanojen joukot ole identtisiä.
Klassinen esimerkki tästä on venäjän sana *мебель*.

Suosittelen tutustumaan näiden termien hyviin Wikipedia-artikkeleihin: 

- [singularia tantum](https://ru.wikipedia.org/wiki/Singularia_tantum)
- [pluralia tantum](https://ru.wikipedia.org/wiki/Pluralia_tantum)


Suku kieliopillisena kategoriana
--------------------------------

### Substantiivien suvun määräytyminen

Substantiivien suvun määrätytyminen on melko monimutkainen ilmiö. Esitettäessä
siihen liittyviä säännönmukaisuuksia voidaan päätyä hyvinkin erilaisiin
kuvausmalleihin. Esittelen tässä kahta vaihtoehtoa.

#### Nikunlassin kuvaus

Ahti Nikunlanssi [-@nikunl: 149] esittää lähtökohtaisesti hyvin yksinkertaisen kaavan, jota
soveltamalla substantiivin suku voidaan määritellä:

1. mies-/urospuolinen = maskuliini. nais-/naaraspuolinen = feminiini
2. 1. deklinaatio = maskuliini, 2. ja 3. deklinaatio = feminiini, 4. ja 5. deklinaatio = neutri
3. taipumaton sana, lyhenne tms. = erillisiä sääntöjä

Deklinaatioiden (типы склонения) käsitteeseen pureudutaan tarkemmin seuraavalla luennolla, joten
selvyyden vuoksi voi olla tarpeen ennen jatkamista tutustua alla olevaan
deklinaatiosta kertovaan materiaaliin.

Perusajatus Nikunlassin kaavassa on, että jokaisen sanan kohdalla katsotaan
ensin, onko sillä merkityksensä puolesta (semanttisesti) jokin suku. Esimerkiksi
*папа* on merkityksen puolesta maskuliini, joten siihen sovelletaan ensimmäistä
sääntöä eikä kaavassa tarvitse edetä pidemmälle. Sanasta *город* ei puolestaan
merkityksen osalta voida vielä sanoa mitään. Tämän vuoksi on katsottava toista
sääntöä. Sana город kuuluu taivutusmuotojensa puolesta ensimmäiseen deklinaation,
joten sen suvuksi määräytyy maskuliini. Sana *умность* puolestaan kuuluu
kolmanteen deklinaatiooon, joten se on feminiini. Sana *море* kuuluu neljänteen
deklinaatioon ja on neutri. 

Taipumattomilla sanoilla ei ole deklinaatiota -- ne eivät nimensä mukaisesti
taivu, joten taivutusmuotojen sarjaakaan ei ole olemassa. Tämän vuoksi näiden
sanojen suvun määrittelemiseen tarvitaan erillisiä sääntöjä. Sama koskee
esimerkimsi lyhenteitä.

#### Šeljakinin kuvaus

Edellistä perinteisempi tapa opettaa suvun määräytymistä on todeta, että äänteisiin X,
Y ja Z päättyvät substantiivit ovat maskuliineja, äänteisiin A, B, C päättyvät feminiinejä ja
äänteisiin  D, E, F taas neutreja. Tätä tapaa noudattaa esimerkiksi Šeljakin
[-@sheljakin: 28--] [ks. myös esimerkiksi @wade2010: 54]. Kuvaus on selkeästi
vähemmän yleistävä kuin Nikunlassilla, mutta toisaalta tarkempi -- se antaa
edellistä kuvausta suorempia vastauksia yhtä konkreettista sanaa koskeviin kysymyksiin.
Esitän seuraavassa tiivistetyn version tästä kuvaustavasta.

Šeljakin lähtee liikkeelle siitä, että sanat voidaan suvun määrätymisen suhteen
jakaa viiteen pääryhmään:

1. Taipuvat substantiivit
2. Taipumattomat substantiivit
3. Useampiosaiset sanat
4. ище- ja ищко-suffikseihin päättyvät sanat
5. Erisnimet

Tarkastelen tässä lyhyesti kahta ensimmäistä ryhmää sekä viimeistä ryhmää.
Eniten huomiota täytyy kiinnittää ensimmäiseen ryhmään, joka onkin määrällisesti
laajin. Tämän ryhmän osalta suku määräytyy seuraavasti:

**Ensiksi**: Yksikön nominatiivin päätteen mukaan seuraavan taulukon kuvaamalla tavalla:

esimerkkisana | nominatiivin pääte     | suku
------------- | ------------------     | ----
книга         | -[а]                   | F
неделя        | -[а]                   | F
море          | -[е]                   | N
тело          | -[о]                   | N
ночь          | pehmeä konsonantti + ø | F
обед          | kova konsonantti + ø   | M
гений         | -[j]                   | M

Tähän määräytymistapaan on kuitenkin seuraavia poikkeuksia tai lisäyksiä.

1. kaikki мя-päätteiset sanat ovat neutreja
2. tietyt kovaan sibilanttiäänteeseen päättyvät ovat feminiinejä -- merkiksi
   tästä lisätään sanan loppuun pehmeä merkki (молодёжь, ложь, дрожь, мышь, роскошь)
3. eräät pehmeään konsonanttiin päättyvät ovat maskuliineja. Suurin tällainen
   ryhmä ovat *тель*-päätteiset sanat. Toinen selkeä ryhmä ovat kuukausien nimet.
   Näiden lisäksi on noin 150 muuta sanaa, jotka päättyvät pehmeään
   konsonanttiin, mutta ovat maskuliineja.

**Toiseksi**: sanan merkityksen mukaan

Yleissääntö on yksinkertainen:

1. Kaikki miespuoliseen henkilöön tai eläimeen viittaavat ovat maskuliineja
2. Kaikki naispuoliseen henkilöön tai eläimeen viittaavat ovat feminiinejä

Tilanne on todellisuudessa kuitenkin mutkikkaampi. Yksi ongelmallinen ryhmä ovat
henkilöihin viittaavat sanat, jotka päätteensä perusteella ovat
maskuliineja. Näihin tapauksiin on seuraavanlaisia ratkaisuja:

1. Kun sana ei ole ammatti, toimeenkuva tai muu vastaava: esimerkiksi *человек*, *враг*,
   *подросток* ja *гений* ovat  aina maskuliineja. (Она -- хороший человек)
2. Ammattia tms. tarkoittavalla sanalla voi olla feminiininen rinnakkaismuoto,
   jota tietyissä tilanteissa voidaan käyttää maskuliinimuodon sijaan
   (студентка, певица, шахматистка ym.).
3. Ammattia tms. tarkoittavalla sanalla ei aina ole feminiinistä rinnakkaismuotoa
   (врач, профессор, доктор, кондуктор). Nämä sanat ovat tavallisesti
   maskuliineja. Tietyissä ympäristöissä suku voi kuitenkin olla feminiini: *в
   гостях была наш врач*.

Lisäksi esimerkiksi sanoilla *плакса*, *убийца*, *пяница*, *коллега*, *умница*
suku määräytyy riippuen kulloinkin puheena olevasta henkilöstä.

Toinen Šeljakinin sanaryhmä ovat taipumattomat substantiivit. Sellaiset
taipumattomat sanat, jotka eivät viittaa henkilöön, ovat yleensä neutreja --
poikkeuksena kuitenkin esimerkiksi sanat *пенальти* ja *кофе*. 

Jos taipumattomat sanat viittaavat henkilöön, niiden suvun määräytyminen
muistuttaa taipuvien henkilöön viittaavien sanojen suvun määräytymistä. Esimerkiksi sanat
*рефери* ja *аташе* vertautuvat tällöihin sanoihin *врач*, *профессор* ym. ja
ovat lähtökohtaisesti maskuliineja. On kuitenkin myös selkeästi feminiinejä
taipumattomia henkilösanoja, esimerkiksi sanat *леди* ja *мадам*.

Jos ei ole välttämätöntä erikseen painottaa taipumattoman eläimen sukua, sen
suku on myös maskuliini: *коричневый кенгуру*, *умный шимпанзе*. Lisäksi
taipumattomien sanojen sisällä on joukko sanoja, joiden suku määräytyy niiden
taustalla olevaan yleisnimeen: kielet, kaupungit ja saaret ovat maskuliineja
(vrt. язык, город, остров), monet joet taas feminiinejä. Lyhenteiden osalta pätee
yleensä lyhenteen pääsanan suku (Московский Государственный **Университет**)

Erisnimistä (viides ryhmä) Šeljakin toteaa, että etunimien suku luonnollisesti
määräytyy sen kantajan mukaan. -он, -ин ja -cкий-päättyvistä sukunimistä on
erikseen feminiiniversio, muista ei.


<!-- https://ru.wiktionary.org/wiki/%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5:%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0-1  -->


Luento 4: sija kieliopillisena kategoriana
====================================================

- [Takaisin sivun ylälaitaan](https://mustikka.uta.fi/~juho_harme/morfologia/#tästä-kurssista)
- [Lataa PDF](http://mustikka.uta.fi/~juho_harme/morfologia/materiaalit/luento4.pdf)
- [Tutki luentokalvoja](http://mustikka.uta.fi/~juho_harme/morfologia/presentations/luento4.html)
- [Tutki tuntitehtäviä](http://mustikka.uta.fi/~juho_harme/morfologia/tehtavat/luento4.pdf)

Sija (падеж) on venäjässä keskeisin nominien taivutuskategoria [@nikunl: 138]. Sijojen
ilmaisuvoima on suuri -- eri sijojen käyttötarkoituksiin pureudutaan tarkemmin
luennoilla 7--9. Tällä luennolla tarkastellaan, mitä sijoja venäjän
sijajärjestelmään kuuluu ja miten substantiiveista eri sijat muodostetaan, toisin
sanoen perehdytään substantiivien taivutussarjoihin eli deklinaatioihin (типы
склонения существительных).

Venäjän sijat
-------------

Venäjän tavallisimmin käytetyt sijat on lueteltu seuraavassa taulukossa:

nimitys (suom)  | nimitys (ven.)     | esimerkki substantiivista
--------------  | --------------     | ---------
nominatiivi     | именительный падеж | курс
genetiivi       | родительный падеж  | курса
datiivi         | дательный падеж    | курсу
akkusatiivi     | винительный падеж  | курса
instrumentaali  | творительный падеж | курсом
prepositionaali | предложный падеж   | курсе

Näiden yleensä mainittujen sijojen lisäksi venäjän sijajärjestelmästä voidaan
erottaa myös eräitä harvinaisempia sijoja. Näistä sijoista [tarkemmin ks. esim. @nikunl: 138-139]
on huomattava, että ne kaikki ovat käytössä vain yksikössä. Harvinaisempien
sijojen mainitsemisella tässä yhteydessä on se funktio, että on hyvä tiedostaa
näiden muotojen olevan selitettävissä todellisuudessa muutenkin kuin vain "poikkeukselliseksi
genetiiviksi", "poikkeukselliseksi prepositionaaliksi" tms. Oiva lähde
pohdittaessa näiden sijojen nimittämistä *sijoiksi* on [tämä Lundin yliopiston
opinnäyte](http://lup.lub.lu.se/luur/download?func=downloadFile&recordOId=3810042&fileOId=3810043)
[@trakymaite2004]. 

**Partitiivinen genetiivi**

Partitiivisen genetiivin (родительный партитивный) muoto on ainoastaan
pienellä joukolla substantiiveja. Esimerkkeinä partitiivisen genetiivin muodoista
voidaan mainita vaikka sananmuodot *чаю*, *народу* ja *снегу*. Partitiivisen
genetiivin käyttö liittyy tilanteisiin, joissa ilmaistan epämääräistä määrää:
*налить чаю*, *стакан сахару*. Nämä voidaan kuitenkin nykykielessä yleensä
korvata akkusatiivilla tai genetiivillä.


**Lokatiivi**

Lokatiivi (местный падеж) esiintyy myös rajoitetulla joukolla substantiiveja.
Sitä käytetään в- ja на-prepositioiden yhteydessä ilmaisemaan paikkaa (*на берегу*). Eron
prepositionaaliin huomaa verratessaan sanaa о-preposition yhteydessä esiintyvään
muotoon: *о береге*. Huomaa myös кровь-sanan yhteydessä lokatiivimuoto *в кровИ* ja
prepositionaali muoto *о крОви*. Tähän ryhmään voidaan lukea myös tyyliltään
puhekieliset muodot *в отпускУ*, *в чаЮ*, joiden kohdalla myös tavallinen
e-päätteinen prepositionaalimuoto on mahdollinen [vrt. @sheljakin: 47].

<!-- http://www.philology.ru/linguistics2/plungyan-02.htm   -->

**Adnumeratiivi**

Adnumeratiivi (аднумератив) koskee käytännössä kolmea substantiivia: шаг, ряд ja
час. Näiden genetiivimuodot ovat шáга, рЯда ja чáса, mutta lukusanojen 2-4 yhteydessä
niistä käytetään muotoja шагá, рядá, часá. 

**Vokatiivi**

Vokatiivin (звательный падеж) muotoja on ennen käytetty säännönmukaisesti
puhuttelun yhteydessä. Tästä jäänteenä ovat edelleen eräät huudahdukset, kuten
*господи!*.

Myös nykyvenäjässä voidaan kuitenkin nähdä olevan vokatiivi puhekielessä. Nämä
muodot lankeavat yhteen monikon genetiivimuodon kanssa, esimerkiksi:
*Мам!/Пап!/Саш!* [@supr2001: 93].


Mitkä ihmeen deklinaatiot?
---------------------------

*Deklinaatiolla* (тип склонения) tarkoitetaan substantiivin taivutusmuotojen
sarjaa. Kielen sanoja tutkittaessa tuskin koskaan on niin, että kaikki sanat
taipuisivat juuri samalla tavalla: kaikkien sanojen genetiivi (jos kielessä
genetiiviä on) muodostettaisiin tietyllä morfilla, kaikkien sanojen akkusatiivi
olisi samoin juuri sama morfi ja niin edelleen. Luonnollisesti asia ei ole
niinkään, että esimerkiksi sijojen muodostaminen olisi täysin sattumanvarainen
prosessi, jossa jokaisen sanan kohdalla sija muodostettaisiin aina eri tavalla.
Todellisuudessa eri lekseemien sananmuotoja tarkastelemalla havaitaan aina, että
tietyt sanat taipuvat samalla tavalla -- muodostavat ryhmiä sen perusteella,
minkälaisin morfein eri sijamuodot toteutuvat.

On kuitenkin tulkintakysymys, mikä lasketaan ryhmäksi. Kuten tällä kurssilla
olemme jo aiemmin huomanneet, ryhmien tai sääntöjen muodostaminen on
tasapainoilua parhaan kuvaustavan löytämiseksi: toisaalta olisi hyvä, että
ryhmiä olisi mahdollisimman vähän (yleistykset olisivat mahdollisimman suuria)
toisaalta ryhmään kuuluminen ei saa olla liian väljää, niin että jouduttaisiin
listaamaan lukemattomia poikkeuksia.

Venäjän substantiiveja voidaan niiden yksikön sijamuotojen perusteella
ryhmitellä monellakin tavalla, ja mikä tapa valitaankin, jäännöksenä syntyy aina
koko joukko sanoja, jotka eivät oikein sovi mihinkään ryhmään ja joita on
pidettävä *lekseemikohtaisina poikkeuksina*.

Venäjän substantiivien jaottelu deklinaatioihin
-----------------------------------------------

Koulukieliopeissa deklinaatiot typistetään usein kolmeen ja todetaan, että
kullakin suvulla on oma deklinaationsa [ks. esim. @wade2010: 73]. Ei kuitenkaan
ole mitään erityistä syytä olettaa, että suvun ja
deklinaation välillä olisi ehdottomasti syy--seuraussuhde,
jossa suku määrää taivutustyypin. Tämän vuoksi seuraavassa esitettävät viisi
deklinaatiotyyppiä [ks. @nikunl: 140--] eivät lankea aivan tarkalleen yksiin
sukujen kanssa. Erityisesti kannattaa kiinnittää huomiota siihen, että
esimerkiksi toiseen deklinaatioon kuuluu myös maskuliineja kuten *мужчина*.

Jos suku ei määrää substantiivin taivutustyyppiä, niin mikä sitten? Jos kyseessä
on johdettu sanavartalo (toisin sanoen, jos sanan vartaloon kuuluu juurimorfin
lisäksi suffikseja), deklinaatiotyyppi määräytyy viimeisen suffiksin mukaan.
Esimerkiksi abstrakteja substantiiveja muodostava *ость*-suffiksi tuottaa
kolmannen deklinaation mukaisen taivutussarjan. Jos taas sanavartalo koostuu
pelkästä juurimorfista, määräytyy deklinaatio juurimorfin mukaan.

### Ensimmäinen deklinaatio

Ensimmäiseen deklinaatioon kuuluvat käytännössä **kaikki maskuliinit**. Ne
on mielekästä ryhmitellä yhteen, koska sijat ilmaistaan niissä koko lailla
samoilla morfeilla. 

- **Nominatiivin** päätteenä on nollamorfi (ø)
- **Genetiivin** päätteenä on /а/. Huomaa, että jos edeltävä konsonantti on
  liudentunut, merkitään morfia kirjoituksessa я-kirjaimella. Itse morfi on
  silti sama vokaali.
- **Akkusatiivin** pääte lankeaa yhteen joko nominatiivin tai genetiivin kanssa
  elollisuudesta riippuen
- **Datiivin** päätteenä on morfi /у/. Jälleen kerran, jos edelätävä konsonantti
  on liudentunut, merkitään morfia kirjoituksessa ю-kirjaimella.
- **Instrumentaalin** päätteenä on morfi /ом/
- **Prepositionaalin** päätteenä on morfi /е/ tai /и/

[^omem]: Tarkkaan ottaen kyseessä on yksi ja sama morfi /ом/, 

Seuraava taulukko kuvaa ensimmäisen deklinaation kootusti esimerkkien kautta:

Sija   | Päätemorfi | esim.1 | esim.2   | esim.3
----   | ---------- | ------ | ------   |
Nom.   | ø          | стол   | учитель  | гений
Gen.   | /а/        | стола  | учителя  | гения
Akk.   | /ø/ ~ /a/  | стол   | учителя  | гения
Dat.   | /у/        | столу  | учителю  | гению
Instr. | /ом/       | cтолом | учителем | гением
Prep.  | /е/ ~ /и   | столе  | учителе  | гении

#### Miten niin /ем/ ei ole oma päätteensä?

Aika todennäköisesti jokin edellisessä taulukossa ja sitä edeltävässä listassa
särähti korvaasi. Näissähän väitetään, että saneissa *учИтелем*, *врачОм*,
*фонарЁм* ja *дОмом* olisi sama instrumentaalia ilmaiseva taivutuspääte.
Kyse on fonologisista seikoista, ja tässä kohden vaadittaneen
pidempää selitystä kuin pelkkä alaviite.

[Ks. esim. море](http://slovonline.ru/slovar_el_fonetic/b-13/id-66515/more.html)


Kuten 

[ks. @nikunl: 87, 139]

ии-pääte гений-sanoilla

### Toinen deklinaatio

Toiseen deklinaatioon kuuluvat -/а/-morfiin päättyvät sanat. Niiden sijapäätteistä
voidaan todeta:

- Nominatiivi ilmaistaan morfilla /а/ (vrt. myös kirjoitusasu)
- Genetiivi ilmaistaan morfilla /и/. Etu- ja taka-i ovat saman [и]-foneemin eri
  variantteja (allofoneja) [ks. @nikunl: 85, 94], joten äänneympäristöstä
  riippuen[^i_ymp] morfi voi edustua joko etisenä tai takaisena.
- Akkusatiivi ilmaistaan morfilla /у/
- Datiivissa on kaksi vaihtoehtoa: /е/ tai /и/
- Instrumentaali ilmaistaan morfeilla /ой/ (tähän morfiin luetaan myös pääte
  *ёй*) ja /ей/. Runokielessä on lisäksi olemassa päätteet /ою/, /ею/.
- Prepositionaali ilmaistaan morfilla /е/ tai /и/

[^i_ymp]: Sanan alussa ja liudentuneen konsonantin jäljessä foneemi [и] edustuu
etu-i:nä, liudentumattoman konsonantin jälkeen taka-i:nä. Lisäksi kun prepositio
ja sitä seuraava sana ääntyvät yhtenä sanana, käyttöön tulee taka-i (с Ирой).
[@nikunl: 77, 94].

Sija   | Päätemorfi | esim.1 | esim.2 | esim.3
----   | ---------- | ------ | ------ | -------
Nom.   | /а/        | книга  | серия  | тыква
Gen.   | /и/        | книги  | серии  | тыквы
Akk.   | /у/        | книгу  | серию  | тыкву
Dat.   | /е/ ~ /и/  | книге  | серии  | тыкве
Instr. | /ой/ ~ /ей/| книгой | серией | тыквой
Prep.  | /е/ ~ /и/  | книге  | серии  | тыкве

### Kolmas deklinaatio

Kolmanteen deklinaatioon kuuluvat liudentuneeseen konsonanttiin päättyvät
feminiinit. Niiden päätteet jakautuvat seuraavasti

- Nominatiivissa ja akkusatiivissa on nollamorfi /ø/ 
- Genetiivissä, datiivissa ja prepositionaalissa /и/
- instrumentaalissa /ju/


Sija   | Päätemorfi | esim.1   | esim.2 |
----   | ---------- | ------   | ------ |
Nom.   | /ø/        | тетрадь  | ночь   |
Gen.   | /и/        | тетради  | ночи   |
Akk.   | /ø/        | тетрадь  | ночь   |
Dat.   | /и/        | тетради  | ночи   |
Instr. | /ju/       | тетрадью | ночью  |
Prep.  | /и/        | тетради  | ночи   |

### Neljäs deklinaatio

Neljäs deklinaatio on hyvin samanlainen kuin ensimmäinen: ainoana erona on
nominatiivi, jota neljännessä deklinaatiossa ei ilmaista nollapäätteellä vaan
päätteillä /о/ ja /е/. Tämä deklinaatio voitaisiin hyvin esittää myös osana
ensimmäistä.

Sija   | Päätemorfi | esim.1 | esim.2 |esim.3
----   | ---------- | ------ | ------ |-------
Nom.   | /о/ tai [е]| место  | поле   | пение
Gen.   | /а/        | места  | поля   | пения
Akk.   | /ø/        | место  | поле   | пение
Dat.   | /у/        | месту  | полю   | пению
Instr. | /ом/       | местом | полем  | пением
Prep.  | /е/ ~ /и/  | месте  | поле   | пении


### Viides deklinaatio

Viidennen deklinaation muodostavat yksinään мя-äänneyhdistelmään päättyvät
substantiivit. Ne ovat kaikki neutreja.


Sija   | Päätemorfi | esim
----   | ---------- | ------
Nom.   | /а/        | время
Gen.   | /и/        | времени
Akk.   | /ø/        | время
Dat.   | /и/        | времени
Instr. | /ом/       | временем
Prep.  | /е/ ~ /и/  | времени


### Monikon deklinaatiot

Esittelen seuraavassa Nikunlassin [@nikunl: 142] ehdotuksen monikon
deklinaatioiksi. Monikkomuotojen muodostuksessa helppoa on, että datiivi-,
instrumentaali- ja prepositionaalimuodot ovat käytännössä aina samat:
muodostetaan päätteillä /ам/, /ами/, ja /ах/. Taivutuksen erot tulevat esille
kaikkein yleisimmissä sijoissa eli nominatiivissa ja genetiivissä. Usein 
[esim. @sheljakin: 44] monikolle esitetäänkin ainoastaan yksi deklinaatio.


#### Ensimmäinen monikon deklinaatio

Monikon nominatiivin ja genetiivin kannalta ensimmäinen ja kolmas deklinaatio
voidaan hyvin yhdistää. Tällöin säännöksi tulee, että nominatiivin pääte on /и/
(muista, että kyseinen morfeemi kattaa sekä etu- että taka-i:n) ja genetiivin
joko /ей/ tai /ов/. Genetiivin päätteen osalta voidaan todeta, että:

- Jos sanan vartalo päättyy parilliseen liudentuneeseen konsonanttiin tai
  konsonantteihin ж, ч, ш, щ, monikon genetiivin pääte on /ей/
- Muussa tapauksessa monikon genetiivin pääte on /ов/


Sija   | Päätemorfi  | esim. 1  | esim.2        | esim. 3    | esim. 4
----   | ----------  | ----     | ------        | ---------- | ---
Nom.   | /и/         | экраны   | выключа́тели   | врач       | ночи
Gen.   | /ей/ ~ /ов/ | экранов  | выключа́телей  | врачей     | ночей
Akk.   | /и/         | экраны   | выключатели   | врачей     | ночи
Dat.   | /ам/        | экранам  | выключа́телям  | врачам     | ночам
Instr. | /ами/       | экранами | выключа́телями | врачами    | ночами
Prep.  | /ах/        | экранах  | выключа́телях  | врачах     | ночах

#### Toinen monikon deklinaatio

Toinen monikon deklinaatio voidaan muodostaa suoraan toisen yksikön deklinaation
pohjalta, niin että monikon nominatiivin pääte on /и/ ja monikon genetiivin
pääte /ø/

Sija   | Päätemorfi | esim. 1
----   | ---------- | ----
Nom.   | /и/        | книги
Gen.   | /ø/        | книг
Akk.   | /и/        | книги
Dat.   | /ам/       | книгам
Instr. | /ами/      | книгами
Prep.  | /ах/       | книгах


#### Kolmas monikon deklinaatio

Kolmas monikon deklinaatio saadaan, kun yhdistetään yksikön neljäs ja viides
deklinaatio. Tällöin voidaan todeta, että monikon moninatiivin pääte on /а/ ja
genetiivin /ø/.

Sija   | Päätemorfi | esim. 1   | esim.2  
----   | ---------- | ----      | ------  
Nom.   | /и/        | времена   | гнёзда  
Gen.   | /ø/        | времён    | гнёзд   
Akk.   | /и/        | времена   | гнёзда  
Dat.   | /ам/       | временам  | гнездам 
Instr. | /ами/      | временами | гнездами
Prep.  | /ах/       | временах  | гнездах 


Luento 5: sija kieliopillisena kategoriana 2
====================================================

- [Takaisin sivun ylälaitaan](https://mustikka.uta.fi/~juho_harme/morfologia/#tästä-kurssista)
- [Lataa PDF](http://mustikka.uta.fi/~juho_harme/morfologia/materiaalit/luento5.pdf)
- [Tutki luentokalvoja](http://mustikka.uta.fi/~juho_harme/morfologia/presentations/luento5.html)
- [Tutki tuntitehtäviä](http://mustikka.uta.fi/~juho_harme/morfologia/tehtavat/luento5.pdf)

Tällä luennolla sijakategoriaa käsitellään vielä taivutusopin kannalta ja
tarkastellaan poikkeuksia edellä esitettyihin deklinaatioihin sekä lisäksi
adjektiivien ja pronominien deklinaatioita. Lopuksi pohditaan sanapainon
vaihtelua eri taivutusmuodoissa.

Sekamuotoja ja poikkeuksia
---------------------------

Edellä lueteltujen viiden taivutustyypin voi nähdä muodostavan selkeimmät
pääryhmät, joihin suurin osa substantiiveista voidaan sovittaa. Näiden
ulkopuolelle jää kuitenkin väistämättä iso joukko substantiiveja. Seuraavassa
esitetään muutamia huomioita ja säännönmukaisuuksia näistä sanoista.

### Muutoksia vartaloissa

#### Äänteenmuutokset

##### Väistyvä vokaali

Ehkäpä merkittävin yksittäinen sanojen sijataivutukseen vaikuttava
morfofonologinen ilmiö on niin sanottu väistyvä vokaali (беглый гласный). Tällä
ilmiöllä  viitataan lähinnä
/о/- ja /э/-vokaalien vaihteluun nollaäänteen/nollavokaalin (нуль
звука/нуль гласного) kanssa. Katsotaan paria esimerkkiä[^nkrjaes]:

(@ee_signal) Световой сигнал выдергивал её из глубокого **сна**.
(@ee_vrazhdeb) Враждебность к **иностранцам** в России глубоко обеспокоила его
(@ee_stat) "Два пункта в справочнике, пара-тройка **статей** в прессе ― это и убило Бернара Луазо"

[^nkrjaes]: esimerkit [kansalliskorpuksesta](http://ruscorpora.ru)

Esimerkkien @ee_signal--@ee_stat lihavoidut substantiivit ovat kaikki sanoja,
joiden taivutusmuodoissa väistyvän vokaalin ilmiö näkyy. Esimerkiksi sananmuodon
*сна* yksikön nominatiivi on с**о**н ja sananmuodon *иностранцам*
иностран**е**ц. Myls sananmuoto *статьей* osuu väistyvän vokaalin piiriin,
vaikkei ensi silmäykseltä siltä näyttäisikään. Katsotaan ilmiötä tarkemmin
Nikunlassin [-@nikunl: 113-114] ja Šeljakinin [-@sheljakin: 59-60] pohjalta.

Nikunlassin mukaan väistyvälle vokaalille voidaan esittää yksinkertainen
perussääntö: jos sananmuodossa väistyvänä vokaalina ilmenevä foneemi esiintyy
**ennen nollapäätettä** (ø), se edustuu konkreettisena vokaalina, muussa tapauksessa
nollavokaalina.

Ajatellaan edellä esitetyn pohjalta sanaa *сон* ja katsotaan sen
taivutusparadigmaa (mukana sekä yksikkö että monikko):


Sija     | Päätemorfi | esim.
----     | ---------- | ----
y.nom.   | ø          | сон 
y.gen.   | /а/        | сна 
y.akk.   | /ø/ ~ /a/  | сон 
y.dat.   | /у/        | сну 
y.instr. | /ом/       | cном
y.prep.  | /е/ ~ /и   | сне 
-------  | ---------  | ---
m.nom.   | /и/        | сны
m.gen.   | /ов/       | снов
m.akk.   | /и/        | сны
m.dat.   | /ам/       | снам
m.instr. | /ами/      | cнами
m.prep.  | /ах/       | снах 


Kuten taulukosta huomataan, ainoa sija, joka edustuu nollapäätteenä, on yksikön
nominatiivi. Edellä esitetyn säännön mukaisesti tällöin myös väistyvä vokaali
esiintyy oikeasti vokaalina, muissa tapauksissa nollaäänteenä. Šeljakinin
[-@sheljakin: 59] luokittelussa *сон* kuuluu ensimmäiseen väistyvän vokaalin
sisältävien sanojen ryhmään. Edellä mainittu статья sekä esimerkiksi sanat
*ведро*, *окно* kuuluvat toiseen, jossa ainoa väistyvän vokaalin sisältävä muoto on
monikon genetiivi. Tämä sopii edellä esitettyyn sääntöön: näillä sanoilla
monikon genetiivi esiintyy nimenomaan nollapäätteenä.


Pohdi tarkemmin ilmiötä tutkimalla esimerkiksi 
seuraavien sanojen taivutusmuotoja (klikkaamalla linkkiä pääset wikisanakirjan
artikkeliin):

- [рот](https://ru.wiktionary.org/wiki/рот),
  [сон](https://ru.wiktionary.org/wiki/сон),
  [ров](https://ru.wiktionary.org/wiki/ров),
  [рожь](https://ru.wiktionary.org/wiki/рожь),
  [лоб](https://ru.wiktionary.org/wiki/лоб),
  [мох](https://ru.wiktionary.org/wiki/мох),
  [лед](https://ru.wiktionary.org/wiki/лед),
  [шов](https://ru.wiktionary.org/wiki/шов),
  [день](https://ru.wiktionary.org/wiki/день),
  [лев](https://ru.wiktionary.org/wiki/лев),
  [пень](https://ru.wiktionary.org/wiki/пень)
- [посол](https://ru.wiktionary.org/wiki/посол),
  [орёл](https://ru.wiktionary.org/wiki/орёл),
  [пепел](https://ru.wiktionary.org/wiki/пепел),
  [котёл](https://ru.wiktionary.org/wiki/котёл)
- [висок](https://ru.wiktionary.org/wiki/висок),
  [дружок](https://ru.wiktionary.org/wiki/дружок),
- [локоть](https://ru.wiktionary.org/wiki/локоть),
  [ноготь](https://ru.wiktionary.org/wiki/ноготь),
- [огонь](https://ru.wiktionary.org/wiki/огонь),
  [корень](https://ru.wiktionary.org/wiki/корень),
- [любимец](https://ru.wiktionary.org/wiki/любимец),
  [перец](https://ru.wiktionary.org/wiki/перец),
- [воробей](https://ru.wiktionary.org/wiki/воробей),
  [муравей](https://ru.wiktionary.org/wiki/муравей),
  [ручей](https://ru.wiktionary.org/wiki/ручей)

Monikon genetiivimuoto *статьей* saattaa vielä hämätä. Miten niin siinä on
väistyvä vokaali? Sanan juurimorfi on tarkkaan ottaen /стать/ eli foneettisesti
tarkemmassa asussa /статj/ (pehmeä merkki ei merkitse tässä kohden pelkkää
liudennusta -- tähän riittäisi pelkkä я-kirjainkin). Nollavokaalin sisältävissä
muodoissa статья taipuu siis cтатьи, статьям jne. Monikon genetiivi on kuitenkin
nollapäätteinen, eli muoto olisi ilman väistyvää vokaalia juurimorfi + ø, toisin
sanoen /статj/ + ø. Tähän nollapäätteen edelle livahtaa väistyvä vokaali е,
jolloin muoto on /статej/ø/. Tätä ei tule sekoittaa /ей/-morfeemiin monikon
genetiivin tunnuksena, vaan monikon tunnus on tässä nollapääte ja vokaali kuuluu
juurimorfiin -- se ei vain esiinny nykykielessä sanan muissa muodoissa.

Kyseessä on siis melko laaja, muttei kuitenkaan automaattinen ilmiö. Se esiintyy
substantiiveilla tiettyjen suffiksien yhteydessä, ei kuitenkaan aina. 
Usein väistyvän vokaalin ennustamisessa auttaakin paitsi suffiksi, myös
sanapaino. Esimerkiksi sanat *америкАнец* ja *инострАнец* sisältävät väistyvän vokaalin,
sana близнЕц ei. Sanat *кОрень* ja *кАмень* sisältävät väistyvän vokaalin, sana
*олЕнь* ei. Lisäksi on todettava, että tiettyjen konsonanttiyhdistelmien läsnä
ollessa nollavokaali ei esiinny, vaikka voisi olettaa: хитрЕц-хитрецА.

#### Muita äänteenmuutostapauksia

Väistyvän vokaalin lisäksi myös eräät muut ilmiöt vaikuttavat substantiivien
sijataivutukseen. Näitä ovat esimerkiksi *х/ш*-vaihtelu ja *к/ч*-vaihtelu:
Ухо/Уха mutta Уши/ушЕй - Око/Ока, mutta Очи/очЕй. Lisäksi sanalla сосед on
monikossa liudentunut vartalo (vrt. yks.gen. соседа - mon.gen соседей). [@nikunl: 141].


#### Yksittäisiä tapauksia

Substantiiveilla мать ja  дочь on useimmissa sijamuodoissa poikkeava vartalo:

Sija   | Päätemorfi | esim.1 
----   | ---------- | ------ 
Nom.   | /ø/        | мать   
Gen.   | /и/        | матери 
Akk.   | /ø/        | мать   
Dat.   | /и/        | матери 
Instr. | /ju/       | матерью
Prep.  | /и/        | матери 

Toinen huomionarvoinen vartalonmuutosten ryhmään osuva sanajoukko ovat
yhdyssanat tyyppiä *полдень*. Nämä sanat voivat saada ylimääräisen у-vokaalin:
*полубутылки*, *полубутылке* jne. Tästä ilmiöstä ei kuitenkaan ole mahdollista
tehdä yleispätevää sääntöä. Esimerkiksi Šeljakin[-@sheljakin: 50] toteaa
(korostus minun):

"При изменении по падежам ... компонент пол **может заменяться** компонентом полу"

Jonkinnäköisenä suuntaviivana voinee sanoa, että у-vokaalin sisältävät muodot
ovat usein tyyliltään kirjallisempia.

Isachenko [-@isachenko2003: 167] mainitsee vielä esimerkiksi seuraavia
poikkeuksellisesti taipuvia sanoja (linkit vievät wikisanakirjan artikkeleihin,
joista voit tutkia taivutusta tarkemmin):
[курица](https://ru.wiktionary.org/wiki/курица),
[чудо](https://ru.wiktionary.org/wiki/чудо),
[небо](https://ru.wiktionary.org/wiki/небо)
[судно](https://ru.wiktionary.org/wiki/судно).

Aivan omanlainen poikkeuksensa on sana
[мечта](https://ru.wiktionary.org/wiki/мечта), jonka monikon genetiivimuoto on
hankala määritellä. Ainoa järkevä ratkaisu on käyttää muotoa *мечтаний*, jonka
voi varsinaisesti nähdä olevan peräisin sanasta *мечтание*.

<!-- ks. kansalliskorpus! 

myös:
http://rus.stackexchange.com/questions/424187/%D0%9F%D0%BE%D0%BB%D1%81%D1%83%D1%82%D0%BE%D0%BA-%D0%BF%D0%BE%D0%BB%D0%BF%D1%8F%D1%82%D0%BE%D0%B3%D0%BE/424190#424190

-->




### Monikkoon liittyviä poikkeuksia

 <!--  Hyvä paikka testata kansalliskorpusta! -->

Monilla 1. deklinaatioon kuuluvilla sanoilla monikon pääte ei ole
odotuksenmukaisesti /и/, vaan /а/. Näin on esimerkiksi seuraavilla sanoilla
[täydellinen lista ks. @sheljakin: 52--53]:

[бок](https://ru.wiktionary.org/wiki/бок), [век](https://ru.wiktionary.org/wiki/век), [глаз](https://ru.wiktionary.org/wiki/глаз), [дом](https://ru.wiktionary.org/wiki/дом), [адрес](https://ru.wiktionary.org/wiki/адрес), [берег](https://ru.wiktionary.org/wiki/берег), [вечер](https://ru.wiktionary.org/wiki/вечер), [лагерь](https://ru.wiktionary.org/wiki/лагерь), [паспорт](https://ru.wiktionary.org/wiki/паспорт), [профессор](https://ru.wiktionary.org/wiki/профессор)

Joillakin substantiiveilla puolestaan on kaksi eri monikkomuotoa, niin että
muodoilla usein on eri merkitys. Tällaisia sanoja ovat esimerkiksi *образ*
(*образы*, 'hahmot' - *образА*, 'ikonit'), *пропуск* (*прОпуски*, 'poissaolot' -
*пропускА*, 'pääsyluvat'), *лист* (*листЫ*, 'paperit/sivut',*лИстья*,'lehdet').

Erityistä huomiota kannattaa kiinnittää sanojen *колено* ja *яблоко* monikoihin.
Sanalla колено on kaksi monikon nominatiivia, joista toinen (коленА) ei viittaa polviin
fysiologisena ilmiönä vaan esimerkiksi Israelin heimoihin Raamatussa;
muoto *колЕни* on se, joka viittaa колено-sanaan sen tutummassa merkityksessä.
Яблоко-sana muistuttaa taivutukseltaan колено-sanaa siinä mielessä, että sekin
noudattaa muuten neljättä deklinaatiota, mutta monikon nominatiivi ei osukaan
edellä monikon kolmanneksi deklinaatioksi määriteltyyn ryhmään vaan ilmaistaan
/и/-morfilla.

### Sekadeklinaatioita

Tietyt sukunimet taipuvat muuten 1. deklinaation mukaan, mutta niiden yksikön
instrumentaalimuoto muistuttaa adjektiivien instrumentaalimuotoa:

Sija   | Päätemorfi | esim. 1  | esim.2
----   | ---------- | ----     | ------
Nom.   | /ø/        | Иванов   | Малкин
Gen.   | /а/        | Иванова  | Малкина
Akk.   | /а/        | Иванова  | Малкина
Dat.   | /у/        | Иванову  | Малкину
Instr. | /ым/       | Ивановым | Малкиным
Prep.  | /е/        | Иванове  | Малкине

Kuitenkin esimerkiksi ук-päätteiset sukunimet saavat normaalin yksikön
instrumentaalin päätteen:

(@ee_mjak) фильм с Малкиным и Ковальчуком


Toinen esimerkki sekadeklinaatiosta on sana
[путь](https://ru.wiktionary.org/wiki/путь), jossa sekoittuvat ensimmäisen ja
kolmannen deklinaation päätteet siten, että instrumentaalin pääte on ensimmäisen
deklinaation mukainen, genetiivi, datiivi ja prepositionaali kolmannen.
Vertailun vuoksi alla on kuvattu myös yksi substantiivi kummastakin
varsinaisesta deklinaatiotyypistä:


Sija   | Päätemorfi | esim 1. | esim. 2
----   | ---------- | ----  
Nom.   | /ø/        | путь  ;
Gen.   | /и/        | пути  
Akk.   | /ø/        | путь  
Dat.   | /и/        | пути  
Instr. | /ом/       | путём 
Prep.  | /и/        | пути  



Deklinaatioista ja painotyypeistä
---------------------------------

Aleksandr Isachenko toteaa laajassa venäjän kieliopin kuvauksessaan seuraavasti
[-@isachenko2003: 129]:

*Морфологическая характеристика имен существительных в русском языке не
ограничивается указанием всех падежных окончаний. Чтобы правильно пользоваться
словом, необходимо усвоить его акцентологические особенности.*

Vapaan sanapainon takia olennaista venäjän substantiivien morfologiassa on paitsi päätteiden tunteminen, 
myös sen tiedostaminen, että eri sananmuotojen ääntämys vaihtelee painon osalta
ja myös painon suhteen sanoja voidaan jossain määrin ryhmitellä.

Tässä yhteydessä ei tehdä erityisen kattavaa katsausta eri painotyyppeihin, vaan
tarkoitus on ennemminkin rohkaista itsenäiseen opiskeluun ja ylipäätään esitellä ajatus.


Luento 6: Vertailuaste. Sijat funktionaalisen morfologian kannalta 1
====================================================================

Luento 7: Sijat funktionaalisen morfologian kannalta 2
====================================================================


Luento 8: Sijat. Elollisuuskategoria.
=====================================

[ks. @sheljakin: 43]

painoasioita: НА пол vs. на Пол

Luento 12 : Pääluokka kieliopillisena kategoriana
=================================================

ks. Vanhala-Aniszewski 1992!


Kirjallisuutta
==============


<!--  !pandoc -t latex --bibliography=lahteet.bib --template=textemp.tex -o a/luento1.tex -->
<!--  !pandoc morfologia.Rmd -f markdown -t html --bibliography=lahteet.bib --standalone -o index.html -css github-pandoc.css --toc --toc-depth=1 --include-after-body=scripts.js --smart -->


