% Morfologia, luento 7
% Juho Härme
% Pinni B 5004, juho.harme@uta.fi


# Sijat funktionaalisen morfologian kannalta 1

# Genetiivi

Tehtävä: 

>1. Etsi tekstistä / esimerkkilauseista genetiivin eri merkityksiä (mitä eri asioita genetiivillä venäjässä ilmaistaan)
>2. Pohdi, millä sijalla / tavalla sama asia ilmaistaan suomessa

# Kootusti

>- Велосипед мальчика  (omistaja)
>- член комитета (rooli)
>- мало/много/сколько/столько/достаточно интересных людей (määrä)
>- Маша моложе Миши (vertailu)
>- часть страны (osa)
>- крыша дома (osa)
>- женщина высокого роста  (ominaisuus)
>- литр воды (mitta)
>- человек твёрдых убеждений (ominaisuus)
>- чтение газеты (objekti)
>- изобретатель самолёта (subjekti)

# Lisää

>- Никита, наевшийся вкусного борща с помидорами, чувствовал невероятную усталость.
>- Давайте лучше выпьем кваса и будем танцевать. 
>- Дедушка уже нарубил дров.
>- Маша привезла овощей
>- Если ребёнок просит конфет, надо ему сначала дать, а потом...
>- Ты хочешь мороженого?

# Rajoituksia / tendenssejä

>- vrt. \*на столе есть яблок
>- наесться.. нарубить... привезти
>- просить / хотеть

# Genetiivi verbin täydennyksenä

>- дополнение/обстоятельство -- täydennys/määrite

<!-- Pari esimerkkilausetta, joista kysytään, mikä tässä täydennys, mikä määrite  -->

>- добиваться, достигать, желать ja заслуживать.
>- ждать/ожидать/дожидаться, искать, просить, хотеть, требовать.
>- бояться, опасаться, пугаться, стесняться, стыдиться, сторониться,  избегать

<!-- Etsitään läppäreillä korpuksesta verbitapauksia ryhmittäin ... valittavana kans.korp ja araneum. Mustikka? -->

# Milloin akkusatiivi?

<article class='incremental' style='float:left;'>
>- Gen = Gen
>- Henkilöt, tarkat viittauskohteet = Akk.
>- ждать, искать, хотеть, просить, требовать
</article>

<article class='incremental nobul' style='float:left;margin-left:2em;font-size:110%;'>
>- Такой способ требует *опыта работы*.
>- Это *требует готовности* клиентов.
>- Теперь заинтересованные стороны *ждут решения* московской экологической экспертизы
>- Жду 23-й автобус
>- Ждем ваши ответы по адресу...
>- Жду вашей реакции 
>- Я с нетерпением ждал Ваше письмо и наконец получил.
>- Крепко тебя целую и давно жду твоего письма
>- Он хочет власти, но не знает верную дорогу к ней.
>- Сказку, сказку, хочу сказку! ― обрадовалась девочка
>- Хочешь папироску?
>- Но она ищет выхода
>- Кто-то страдал от одиночества, кто-то искал взаимопонимания
>- Теперь мы не ищем работу, работа находит нас
>- В каждом приборе, аппарате я прежде всего ищу кнопку "стоп"!
>- Начальство требует конкретику
>- Азакуан требует лошадь, а не Куклу…
>- Излечение действительно требует усилий и времени
>- Общие угрозы требуют объединения усилий России с США
</article>


# Genetiivi + kieltomuoto

>- Tutkittu, huomiota herättänyt ilmiö kielitieteessä (genetive of negation)
>- Useammin kuin luuletkaan -- vertaa esim. *puola*
>- Subjektina & objektina
    - нет + не пападалось, не встречалось, не сохранилось  + muita
    - abstraktius, gen=gen-sääntö
>- [Tehtävä]()


# Suuntaviivoja?



<!-- Käännöslaus!-->


<!--  pandoc -f markdown -s luento7.rmd -t slideous -o luento7.html --self-contained --include-in-header=fontheader.html --smart -->

