% Morfologia, luento 17
% Juho Härme
% Pinni B 5004, juho.harme@uta.fi

# Aspektinvalinnan koordinaatteja

[Tehtävä viime kerralta](../tehtavat/luento16.pdf)

>- 1. Konkreettis--faktinen merkitys ja konkreettis-prosessuaalinen merkitys
>- 2. Konkreettis--faktinen merkitys ja rajoittamattoman toiston merkitys
>- 3. Summatiivinen merkitys ja rajoittamattoman toiston merkitys
>- 4. Konkreettis--faktinen merkitys ja yleisesti toteava merkitys
>- 5. Perfektin merkitys ja yleisesti toteava merkitys
>- [Tehtävä](../tehtavat/luento17.pdf)

# Aspektin valinta futuurissa

>- Imperfektiivinen aspekti: aikomus, epävarmuus, toisto
>- Perfektiivinen aspekti: varmuus, päättäväisyys, yksittäinen kerta

# Aspektin valinta kieltolauseissa

>- Imperfektiivisen aspektin laajentunut käyttöala
>- Kielletäänkö toiminnan alkaminen vai loppuun saattaminen?
>- Olisiko jonkin toiminnan pitänyt tapahtua?
>- Onko yhteys nykyhetkeen?
>- Kielletäänkö pakko / tarve yms.?
>- Kielletäänkö mahdollisuus?

# Aspektin valinta infinitiivitapauksissa

>- Vaihetta ilmaisevat verbit
>- Aina tulosta painottavat verbit
>- Imperfektiivinen yleensä toistoa
>- Jos yksittäinen tapaus -> yleensä perfektiivinen aspekti
>- Мне надо *поговорить* с ним
>- Я хочу *прочитать* эту книгу

# Teonlaadut = Способы действия


<article class="vinx" style="font-size:120%;color:green;">
>- Когда за Иваном хлопнула дверь, Ирина *заплакала*.
>- Как будто я должен тут просто *запеть* от радости. 
>- Только что деревья были голыми, вдруг все *зазеленело*, началось цветение деревьев
</article>

<article class="vinx" style="font-size:120%;color:brown;">
>- Мне нужно с тобой поговорить.
>- Покурил я, воздухом подышал, легче стало.
>- Легко представить, как хорошо чувствует себя человек, с которым поработал талантливый массажист.
</article>

<article class="vinx" style="font-size:120%;color:purple;">
>- Как мне потом сказали, проспал я 14 часов
>- Чингисхан проболел всю зиму 1225—1226 гг.
>- В этот раз без света просидели недолго, всего пару часов.
</article>

<article class="vinx" style="font-size:120%;color:red;">
>- Вдруг кто-то кашлянул сзади него.
>- Сын мой засмеялся, махнул рукой, и сказал: "..."
>- Собака, не выдержав такого хамского отношения, *гавкнула* и, не исключено что случайно, *боднул* бабушку, от чего она повалилась на землю.
</article>

<article class="vinx" style="font-size:120%;color:blue;">
>- Довольно *нашутились* мы, пора и за дело! 
>- Бывает, что *наешься* только салатом так, что другого ничего и не хочется.
>- Да, *насмотрелся*, *нарадовался*, весеннего речного воздуха полной грудью *надышался*.
</article>


