% Morfologia, luento 4
% Juho Härme
% Pinni B 5004, juho.harme@uta.fi


# Sija kieliopillisena kategoriana

>- Funktionaalisen morfologian kannalta
>- **Taivutusopin kannalta**
>- Substantiivit, adjektiivit, pronominit, partisiipit, lukusanat

# Venäjän sijajärjestelmä

<!--  Vuorotellen oppilasjärjestyksessä, kukin luettelee sijan suomeksi ja venäjäksi + jonkin substantiivin tässä sijassa -->
<!--  Kierrätä langatonta näppistä? :P -->

<table>
<thead>
<tr class="header">
<th align="left">nimitys (suom)</th>
<th align="left">nimitys (ven.)</th>
<th align="left">esimerkki substantiivista</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
</tr>
<tr class="even">
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
</tr>
<tr class="odd">
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
</tr>
<tr class="even">
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
</tr>
<tr class="odd">
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
</tr>
<tr class="even">
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
<td align="left"><input type="text"></td>
</tr>
</tbody>
</table>

# Harvinaiset / katoavat sijat (funktionaalista morfologiaa)

>- Родительный партитивный
>- Местный падеж
>- Аднумератив
>- Звательный падеж
>- [tehtävä](../tehtavat/luento4.pdf)

# Mikä on deklinaatio?

<article class='incremental nobul' style='font-size:140%; float:left;margin-right:1em;'>
>- книг/а/
>- книг/и/
>- книг/у/
>- книг/е/
>- книг/ой/
>- книг/е/
</article>

<article class='incremental nobul' style='font-size:140%; float:left;margin-right:1em;'>
>- кукл/а/
>- кукл/ы/
>- кукл/у/
>- кукл/е/
>- кукло/й/
>- кукл/е/
</article>

<article class='incremental nobul' style='font-size:140%; float:left;margin-right:1em;'>
>- лёгкость
>- лёгкости
>- лёгкость
>- лёгкости
>- лёгкости
>- лёгкости
</article>

# 

>- Deklinaatio vs. suku
>- Tulkintakysymys!
>- poikkeusjäämä
>- minä oppijana -- minä opettajana?



# Tehtävä (substantiivien deklinaatiot)

>- Jakautukaa 2--3 hengen ryhmiin vierekkäin istuvien kesken (yhteensä 4--5 ryhmää).
>- Tehtävä 1: erottele deklinaatiosta päätteet?
>- Tehtävä 2: keksi esimerkkisanoja deklinaatioon, josta vain päätteet annettu


<!--  pandoc -f markdown -s luento4.Rmd -t slideous -o luento4.html --self-contained --include-in-header=fontheader.html --smart -->



