% Morfologia, luento 15
% Juho Härme
% Pinni B 5004, juho.harme@uta.fi

# Venäjän aikamuodot


<article class='incremental'>
<table>
<thead>
<tr class="header">
<th align="left">Aika</th>
<th align="left">muoto1</th>
<th align="left">muoto 2</th>
</tr>
</thead>
<tbody>
<tr class="incremental odd">
<td align="left">Mennyt (preteriti)</td>
<td align="left">прошедшее несовершенное</td>
<td align="left">прошедшее совершенное</td>
</tr>
<tr class="incremental even">
<td align="left">Nykyhetki (preesens)</td>
<td align="left">настоящее несовершенное</td>
<td align="left">-</td>
</tr>
<tr class="incremental odd">
<td align="left">Tuleva (futuuri)</td>
<td align="left">будущее несовершенное</td>
<td align="left">будущее совершенное</td>
</tr>
</tbody>
</table>
</article>

<article class='incremental' style='margin-top:3em;'>

## ОТКРЫТЬ / ОТКРЫВАТЬ

<table>
<thead>
<tr class="header">
<th align="left">Aika</th>
<th align="left">muoto1</th>
<th align="left">muoto 2</th>
</tr>
</thead>
<tbody>
<tr class="incremental odd">
<td align="left">Mennyt (preteriti)</td>
<td align="left">открывал</td>
<td align="left">открыл</td>
</tr>
<tr class="incremental even">
<td align="left">Nykyhetki (preesens)</td>
<td align="left">открываю</td>
<td align="left">-</td>
</tr>
<tr class="incremental odd">
<td align="left">Tuleva (futuuri)</td>
<td align="left">буду открывать</td>
<td align="left">открою</td>
</tr>
</tbody>
</table>
</article>



<!-- 

Pikku esitys luokassa. Pyydetään jotakuta HITAASTI ottamaan kirjan ja ryhtymään
avaamaan sitä. Kesken avaamisen keskeytetään ja huudetaan "Pekka! Mitä sä teet?"
Mietitään vastausta "avaan kirjaa". Käännetään venäjäksi.

- piirrä taululle janat
- piirrä taululle I ja P

- Kotitehtäväksi preteritin ja futuurin muodostamista? Kysytään ensi tunnin alussa, oliko ongelmia.

-->


# Aikamuotojen muodostus

<article style="float:left;">

## Mennyt aika

<article class='vinx' style='color:green;font-size:200%;'>
>- ИГРАЛ
>- ПРОСИДЕЛИ
>- ЛЮБИЛ
>- КООРДИНИРОВАЛА
>- ПОВЛИЯЛО
</article>

<article class='vinx' style='color:purple;font-size:200%;'>
>- ПОГИБЛА
>- ВЫТЕР
>- ОСТЫЛО
>- ДОСТИГЛИ
>- ПОПАЛ
</article>

</article>

<article style="float:left;margin-left:2em;">

## Ei-mennyt aika

<article class='vinx' style='color:green;font-size:200%;'>
>- РАССМАТРИВАЮ
>- БУДУ РАССМАТРИВАТЬ
>- РАССМОТРЮ
</article>

</article>


# ASPEKTI ja aspektuaalisuus

>- Miten suomi ilmaisee aspektuaalisuutta?
>- РУБАШКОЙ
>- ПРОГУЛЯТЬ
>- Kieliopillinen kategoria =
>- piirre, jonka suhteen kaksi muotoa oppositiossa
>- Mikä piirre aspektissa?

# Esimerkkejä

<article class='vinx' style='color:red; font-size:130%;'>
>- Ели пиццу / съели пиццу
>- ужинали / поужинали ..
>- буду смотреть / посмотрю на улицу
>- Соседи всю ночь шумели!
>- Соседи прошумели 9 часов
>- После ужина мы посидели на траве 
>- Все засмеялись
>- Выигрывал ли зенит лигу чемпионов?
>- Выиграл ли зенит лигу чемпионов?
>- Дети, вы уже накупались?
>- Маша всегда тебе поможет!
>- Вы не брали со стола Фломастер? Он же не на том месте лежит!
>- Кто взял со стола Фломастер?
>- Ты будешь обедать?
</article>

[TEHTÄVÄ](https://learning2.uta.fi/mod/resource/view.php?id=430417)

# Piirteitä

>- Toiminnan käsittäminen kokonaisuutena
>- Prosessuaalisuus
>- Kesto
>- Toiminnan samanaikaisuus ja peräkkäisyys

# Общие и частные видовые значения

<article class='incremental vinx' style="font-size:200%;float:left;margin-left:2em;">

>- <span color='purple'>Конкретно-процессное значение</span>
    - Вечером я буду смотреть телевизор
    - Вчера мы с сыном играли с поездами 
    - Потом бросился в кухню, где на плите варился бульон
>- <span color='aliceblue'>Конкретно-фактическое значение</span>
    - Он повторил мне свой вопрос
    - Наша команда победил матч с командой университета Турку 
    - Завтра я куплю тебе пластилину.

</article>


# Aspektipari

>- Määritelmä: Kaikki muu samaa -- ero ainoastaan aspektissa
>- Miten eristää "aspektuaalisuus" muusta merkityksestä?
>- Toiset parit selvempiä kuin toiset
>- "Klustereita"?

# Aspektiparien muodostus

<article style="float:left;margin-left:2em;">

### Miten imperfektiivisen aspektin verbistä saa perfektiivisen?

>- ужинать
>- видеть
>- лгать
>- благодарить
</article>

<article style="float:left;margin-left:2em;">

### Miten perfektiivisen aspektin verbistä saa imperfektiivisen?

>- открыть
>- прочитать
>- получить
>- толкнуть

</article>

# Aspektinmuodostuskeinot

>- Prefiksaatio
>- Suffiksaatio
>- Suppletiivisuus:
    - говорить - сказать
    - брать - взять
    - класть - положить
>- [Tarkemmin](http://people.uta.fi/~harme.juho.k/aspekti-ja-liikeverbiteoria/aihekokonaisuudet/aspektin_muodostus_pres.html#/slide-6)



